# Generated by Django 3.2.22 on 2023-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeslist',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
